name: myosis
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-asus-nvidia
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: akmods
    base: asus
    install:
      - winesync
      - xpadneo
      - xone

  - type: bling
    install:
      - laptop

  - type: rpm-ostree
    install:
      - fastfetch
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox

  - type: signing
