name: myosis
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-asus-nvidia
image-version: latest 

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - fastfetch
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox

  - type: signing
